### ISSUE TITLE
CBC plugin not working

### ISSUE THREAD

**Issue by crocdav** [micahg/plugin.video.cbc#13]
For the last couple of weeks, the CBC plugin has stopped working. Seems to have reached an end of file. Perhaps the site changed with the Olympics.

**Comment by micahg** [comment]
Hello,

I just tested CBC toronto (live channel) and the first episode of the CBC's greatest ever drama, 21 Thunder. Both work for me.

Can you submit a log or give some more details about what exactly is not working?

Thanks,

**Comment by crocdav** [comment]
Hi Micah,

Here's the relevant section in the logfile. I suspect it is something on my
end, but any pointers to what's happening would be greatly appreciated.

Thanks,

Dave

2021-08-10 15:40:12.370 T:16096    INFO <general>: CPythonInvoker(79,
/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/default.py):
script successfully run
2021-08-10 15:40:13.484 T:16096    INFO <general>: Python interpreter stopped
2021-08-10 15:40:15.345 T:16106    INFO <general>: initializing python engine.
2021-08-10 15:40:16.211 T:16106 WARNING <general>: xbmc.translatePath
is deprecated and might be removed in future kodi versions. Please use
xbmcvfs.translatePath instead.
2021-08-10 15:40:16.216 T:16106   ERROR <general>: EXCEPTION Thrown
(PythonToCppException) : -->Python callback/script returned the
following error<--
                                                    - NOTE: IGNORING
THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class
'EOFError'>
                                                   Error Contents: Ran
out of input
                                                   Traceback (most
recent call last):
                                                     File
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/default.py",
line 245, in <module>
                                                       liveChannelsMenu()
                                                     File
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/default.py",
line 127, in liveChannelsMenu
                                                       chans = LiveChannels()
                                                     File
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/resources/lib/livechannels.py",
line 13, in __init__
                                                       session_cookies
= loadCookies()
                                                     File
"/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.cbc/resources/lib/utils.py",
line 35, in loadCookies
                                                       cookies = pickle.load(f)
                                                   EOFError: Ran out of input
                                                   -->End of Python
script error report<--

2021-08-10 15:40:17.369 T:16106    INFO <general>: Python interpreter stopped
2021-08-10 15:40:17.383 T:16105   ERROR <general>: GetDirectory -
Error getting plugin://plugin.video.cbc/?menu=Live%20Channels
2021-08-10 15:40:17.388 T:12044   ERROR <general>:
CGUIMediaWindow::GetDirectory(plugin://plugin.video.cbc/?menu=Live%20Channels)
failed

**Comment by micahg** [comment]
OK, that looks like a file error - likely it was corrupted (like if the disk ran out of space).

I'm not sure how to fix it without clearing your user data.

**Comment by crocdav** [comment]
Would clearing my user data affect all my other plugins as well?

Can I replace the file in question?

Thanks

Dave
________________________________

**Comment by micahg** [comment]
Yes clearing would affect your other plugins I expect.  Short term I'm not sure what your fix is if you don't have file system access.

**Comment by crocdav** [comment]
I do have file system access if that helps.
________________________________

**Comment by micahg** [comment]
OK, probably just delete that one file (cookies in the user data folder for the addon).

**Comment by crocdav** [comment]
I'll give that a try when I get home and let you know.

Thanks
________________________________

**Comment by crocdav** [comment]
That worked perfectly.

Thanks Micah!

Dave
________________________________

**Comment by micahg** [comment]
FWIW, future release (4.0.8 and beyond) should resolve this with a "logout" from the settings @crocdav

**Comment by micahg** [comment]
https://github.com/micahg/plugin.video.cbc/commit/b3248d43b4492a114831cf915919ab2159d9940b

**Comment by crocdav** [comment]
Thanks Micah!

Dave

________________________________
