### ISSUE TITLE
Possible change in API somehow/somewhere

### ISSUE THREAD

**Issue by mshiels** [micahg/plugin.video.cbc#16]
I too have code based on the clearleap api, but noticed this morning on gem.cbc.ca Ripper Street is listed as streaming on the 3rd, but when you pull the clearleap list - no Ripper Street.  Checked Murdoch Mysteries that in gem is already showing season 15 but no season 15 in clearleap.  Dang - does that mean they have moved to some new repository??

**Comment by micahg** [comment]
Can confirm -- just compared android app (which already has the first two episodes of Race Against The Tide up) to this, which has just the promo.

Did you find a fix?

**Comment by micahg** [comment]
yeah, they have left behind clearleap -- the new API is better... but not for Kodi...

**Comment by mshiels** [comment]
So any tidbits to get going on the api?

**Comment by micahg** [comment]
yeah -- i am going to get my IPTV manager changes into the official repo and then start work on the v2 api. Which app do you run?

**Comment by mshiels** [comment]
youtube_dl, but unsure of the future of that.

**Comment by micahg** [comment]
Fixed in 4.0.11

**Comment by gedakc** [comment]
> yeah, they have left behind clearleap

Recently (in the past day or so) it appears that some of the web addresses associated with clearleap have disappeared.  This has caused the add-on to fail when trying to load cookies.

The site is: `'https://api-cbc.cloud.clearleap.com/`

Note that I am unable to resolve this name so it has dissappeared at least for me.

```
$ nslookup api-cbc.cloud.clearleap.com
Server:         192.168.1.1
Address:        192.168.1.1#53

** server can't find api-cbc.cloud.clearleap.com: NXDOMAIN
```

The site clearleap.com can be found:

```
$ nslookup clearleap.com
Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
Name:   clearleap.com
Address: 216.146.46.10
Name:   clearleap.com
Address: 216.146.46.11
```

Perhaps there is a new way for cookies to work with the V2 API?

**Comment by micahg** [comment]
Its fixed in https://github.com/xbmc/repo-plugins/pull/3733 -- 4.0.11 works on matrix. update.
