### ISSUE TITLE
Issues running on raspberry pi

### ISSUE THREAD

**Issue by nquesada** [micahg/plugin.video.cbc#18]
Hi --- I am trying to run the addon version 4.0.6 for watching live shows. When I look at what is being printed to `~/.kodi/temp/kodi.log` I find this:

 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
<                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
<                                             Error Type: <type 'exceptions.UnicodeEncodeError'>
<                                             Error Contents: 'ascii' codec can't encode character u'\u2013' in position 17: ordinal not in range(128)
<                                             Traceback (most recent call last):
<                                               File "/home/osmc/.kodi/addons/plugin.video.cbc/default.py", line 237, in <module>
<                                                 liveChannelsMenu()
<                                               File "/home/osmc/.kodi/addons/plugin.video.cbc/default.py", line 129, in liveChannelsMenu
<                                                 labels = cbc.getLabels(channel)
<                                               File "/home/osmc/.kodi/addons/plugin.video.cbc/resources/lib/cbc.py", line 162, in getLabels
<                                                 labels['title'] = '{} {}'.format(item['cbc$callSign'], item['title'])
<                                             UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 17: ordinal not in range(128)
<                                             -->End of Python script error report<--
< 2021-09-12 10:41:59.087 T:1240420576   ERROR: GetDirectory - Error getting plugin://plugin.video.cbc/?menu=Live%20Channels
< 2021-09-12 10:41:59.090 T:1915912208   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.cbc/?menu=Live%20Channels) failed

Any ideas how to fix this issue?

**Comment by micahg** [comment]
4.0.6 is old. Please update.
