### ISSUE TITLE
kodi throws an error

### ISSUE THREAD

**Issue by oshanrube** [micahg/plugin.video.cbc#2]
kodi is throwing "ERROR: OpenDemuxStream - Error creating demuxer" 
may be the player cannot handle the resolution?

> 19:32:15.881 T:1925667328  NOTICE: VideoPlayer: Opening: https://cbcvott-a.akamaihd.net/p//38e815a-00c9a1b4560//CBC_21_THUNDER_SEASON_01_S01E00-v2-13270746/CBC_21_THUNDER_SEASON_01_S01E00-v2-13270746__desktop.m3u8?cbcott=st=1545919328~exp=1546005728~acl=/*~hmac=cc9ba2a4b3bdbf7385dcf094c2b4611fa96237d102456d90e3b2266b2ddaa8e6
19:32:15.882 T:1925667328 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
19:32:16.176 T:1330639616  NOTICE: Creating InputStream
19:32:22.655 T:1330639616  NOTICE: Creating Demuxer
19:32:57.394 T:1330639616   ERROR: OpenDemuxStream - Error creating demuxer
19:32:57.395 T:1330639616  NOTICE: CVideoPlayer::OnExit()
19:32:57.399 T:1925667328   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.cbc/?image=https%3A%2F%2Fi.watch.cbc.ca%2Fp%2F38e815a-00c9a1b4560%2FCBC_21_THUNDER_SEASON_01_S01E00-v2-13270747.jpg&labels=plot%3D21%2BThunder%2Bis%2Bthe%2Bstory%2Bof%2Bthe%2BMontreal%2BThunder%2BU21%2Bteam%2Band%2Bthe%2Bobstacles%2B-%2Bboth%2Bon%2Band%2Boff%2Bthe%2Bfield%2B-%2Bthat%2Bthey%2Bmust%2Bovercome.%26plotoutline%3D21%2BThunder%2Bis%2Bthe%2Bstory%2Bof%2Bthe%2BMontreal%2BThunder%2BU21%2Bteam%2Band%2Bthe%2Bobstacles%2B-%2Bboth%2Bon%2Band%2Boff%2Bthe%2Bfield%2B-%2Bthat%2Bthey%2Bmust%2Bovercome.%26episode%3D0%26title%3D21%2BThunder%2BTrailer%26country%3DCanada%26tvshowtitle%3D21%2BThunder%26mediatype%3Dvideo%26mpaa%3D14A%26studio%3DCanadian%2BBroadcasting%2BCorporation%26season%3D1%26genre%3DDrama&video=True&smil=https%3A%2F%2Fapi-cbc.cloud.clearleap.com%2Fcloffice%2Fclient%2Fweb%2Fplay%2F%3FcontentId%3D8a0475fb-3244-400d-908e-447d6e444870%26categoryId%3D1a5cc774-dc01-4381-a513-f273abfd0345]

**Comment by micahg** [comment]
Hey, I've seen this for a few other people. This isn't something I can fix though -- its an issue with kodi, so far as I can tell.

Worse, I cannot repro it with any of my systems.

Once Leia comes out I'm hoping to add an option to use inputstream instead of ffmpeg to see if it helps.

**Comment by oshanrube** [comment]
Iv tried both kodi on osmc and Android, but couldn't get the video to stream :( what system are you using?

**Comment by micahg** [comment]
android (mi box, firestick), ubuntu and windows. All running Leia RC's right now and all functioning properly.
