### ISSUE TITLE
Kodi 403 Error

### ISSUE THREAD

**Issue by vetmiker** [micahg/plugin.video.cbc#3]
I am getting a 403 Error when I try to load live streams:

2019-03-21 08:35:28.006 T:15588   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
2019-03-21 08:35:28.006 T:15588   ERROR: CCurlFile::Open failed with code 403 for https://cbclivedai4-i.akamaihd.net/hls/live/567230/event2/CBRT/master.m3u8?hdnea=ip=97.107.190.206~st=1553175296~exp=1553175686~acl=/*~id=1cc4759e-c18e-42d7-8f30-6065ad5d12ca~hmac=ddaba512567e594440dfbdc0da52c1f7ab920b1b66ec6f704360de9146b36558:

One thing worth noting is that the IP address listed above is NOT my IP - I wonder if somehow one of the libraries isn't passing along the correct IP, and that is causing the permission denied issue?

CBC loads fine on Android/Windows native clients, but won't load on Kodi 18.1 in Windows or Android. This plugin does, however, work fine in LibreELEC 9.0.1 with identical settings.

Thanks for your help!

**Comment by micahg** [comment]
what show/episode/etc.

**Comment by vetmiker** [comment]
Thanks for taking time to look into this!

Shows/episodes actually work fine. It's live streams under the "Live Channels" that don't work - I tested a bunch of them - Edmonton, Calgary, Vancouver etc.

**Comment by micahg** [comment]
Still? I've tested these just now on a few systems -- everything is working. You are in Canada?

**Comment by vetmiker** [comment]
Micah - sorry for letting this hang out there. CBC came out with a Gem app for Fire TV, so I'm using that instead of Kodi for streaming CBC now. I'm still not sure why in my case it didn't work (Gem works fine on the exact same stick that has Kodi/CBC on it), but this ticket can be closed since it appears it's working for others and I'm good now. Thanks again for taking time to look into this and for your work on the addon!
