### ISSUE TITLE
Live TV Menu Item under Featured

### ISSUE THREAD

**Issue by newf276** [micahg/plugin.video.cbc#30]
Hi, first off, thank you so much for this fantastic addon.  Not sure if this is a bug, or just a feature that is not fully implemented as of yet.

In short, the main menu has Live Channels listed, and when I select it, I can see all the channels, and each one works perfectly when I selct one to play.

The issue I am having is after I select the Featured menu on the main menu, which then basically brings me into the content of CBC Gem I suspect.  In that sub menu, I have at the top, Live TV, however when I select it, it takes me to the list of channels as expected, which appears to be identical to the Live Channels list on the Main Menu. However, when I select any of the channels listed under here, it takes me to nowhere other than the default video menu, which list, TV SHows, Files, video addons etc. I have no idea as to why none of the listed channels in here work at all, considering the same channels work fine under the Main Menu Live Channel item.

Any idea why this does not work, or is it a left over form something that you intended to remove or change later in another future release?

I am authorized, I even have a paid CBC Gem account which is what I use to authorize the addon.  Every other menu item works as expected, just not the Live TV Menu under the Featured menu.  Any thoughts on what maybe causing this?

Thanks again, I very much appreciate all the effort that goes into something like this.

cheers

Ian

**Comment by micahg** [comment]
The working live channels menu is based off an XML manifest file that lists out the channels.

The one of their featured menu abandons the GEM API and does some javascript in-browser with that same XML file IIRC. So I just choose to ignore it and I'm assuming that most people looking for live TV will do the same.

If they ever work it into the API and drop the XML I'll make sure it works.

**Comment by newf276** [comment]
Okay thanks for the explanation, again appreciate the work and effort on this great addon.

**Comment by newf276** [comment]
#micahg

Thanks very much, works perfectly now.  I appreciate you following up on this, your efforts in helping us non programmers is outstanding.  Cheers brother.
