### ISSUE TITLE
Canadian Broadcasting Corp (CBC) add-on authentication broken

### ISSUE THREAD

**Issue by greenmr** [micahg/plugin.video.cbc#34]
I'm not sure when this started because I haven't used the add-on in a few weeks, but now I can browse shows as before but attempts to play them result in the error "Authorizatoin [sic] Failed". Reauthorizing the add-on doesn't help. Using the same login credentials with the web version of CBC Gem and the official Gem Android app both work fine. It is just the Kodi add-on which has stopped working. I have tried this on multiple FireTV, Android, and Windows 10 devices, all running Kodi 19.6.

It appears that the CBC has changed the Gem authorization protocol.

**Comment by micahg** [comment]
Hey,

Yes - you are correct - they've changed the auth (and gotten rid of the old auth system).  I'm working on it - thanks.

**Comment by darealShadow** [comment]
Hey @greenmr,

any idea on timeline? Anything you need assistance with?

Thank you for the plugin. I love it.

**Comment by micahg** [comment]
Hey, its on my list with a few other things... no timeline for now. Sorry.
